---

- name: awx > client > Install tools
  include_tasks: install.yml

- name: awx > client > Configure tools
  include_tasks: config.yml
  when: awx_tower_config is defined and awx_tower_config is not none
